"""Daily digest generator.

Per AGENTS.md §6: every day at 08:00 local time, write a digest containing
the required fields.  The digest is markdown, placed in reports/digests/.

The digest is generated by the autonomous loop's "tick" function — it checks
whether a digest is due each time it polls (every 60 s by default).
"""

from __future__ import annotations

import json
from datetime import datetime, date, timezone
from pathlib import Path
from typing import Any

from peach_loop.ops.logger import get_logger
from peach_loop.ops.state import RunState, total_elapsed_seconds, phase_elapsed_seconds

log = get_logger("digest")


REQUIRED_FIELDS = [
    "phase_status",
    "budget_pct",
    "wall_clock",
    "eta_checkpoint",
    "last_24h_summary",
    "tier2_events",
    "tier1_events",
    "pending_decisions",
    "forecast",
    "plot_path",
]


def is_digest_due(state: RunState, schedule_hour: int = 8) -> bool:
    """True if it is at or past schedule_hour today and no digest has been written today."""
    now_local = datetime.now()  # local time, matching AGENTS.md "human's local timezone"
    today = now_local.date().isoformat()

    if state.last_digest_date == today:
        return False  # already generated today

    return now_local.hour >= schedule_hour


def generate_digest(
    state: RunState,
    config: Any,
    output_dir: Path,
    extra_context: dict | None = None,
) -> Path:
    """Write a daily digest markdown file and return its path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    now = datetime.now()
    filename = f"digest_{now.strftime('%Y-%m-%d_%H-%M')}.md"
    out_path = output_dir / filename

    context = _build_context(state, config, extra_context or {})
    content = _render_digest(context)

    with open(out_path, "w") as f:
        f.write(content)

    state.last_digest_date = now.date().isoformat()
    log.info(f"Daily digest written: {out_path}")
    return out_path


def _build_context(state: RunState, config: Any, extra: dict) -> dict:
    phase_cap_hours = _get_phase_cap(state, config)
    elapsed_phase = phase_elapsed_seconds(state)
    budget_pct = 0.0
    if phase_cap_hours > 0:
        budget_pct = min(100.0, 100.0 * elapsed_phase / (phase_cap_hours * 3600))

    total_elapsed = total_elapsed_seconds(state)
    wall_clock_str = _format_duration(total_elapsed)

    # ETA: rough linear projection to end of phase
    remaining_sec = max(0.0, phase_cap_hours * 3600 - elapsed_phase)
    eta_str = _format_duration(remaining_sec) if remaining_sec > 0 else "cap already hit"

    # Recent tier-2 events (last 24 h)
    recent_tier2 = [e for e in state.tier2_events if _within_hours(e.get("ts", ""), 24)]
    tier1_events = state.tier1_events  # all of them — should be empty if running cleanly

    return {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M local"),
        "phase": state.current_phase,
        "phase_status": state.phase_status,
        "budget_pct": f"{budget_pct:.1f}%",
        "wall_clock": wall_clock_str,
        "eta_checkpoint": eta_str,
        "tier2_events": recent_tier2,
        "tier1_events": tier1_events,
        "pending_decisions": state.pending_decisions,
        "last_24h_summary": extra.get("last_24h_summary", "_No summary provided._"),
        "current_loss": extra.get("current_loss", "_Not available._"),
        "eval_results": extra.get("eval_results", "_Not available._"),
        "runs_completed": extra.get("runs_completed", 0),
        "forecast": extra.get("forecast", "_No forecast available._"),
        "plot_path": extra.get("plot_path", "_No plot available._"),
    }


def _render_digest(ctx: dict) -> str:
    lines = [
        f"# Daily Digest — {ctx['generated_at']}",
        "",
        "## Status",
        f"- **Phase:** {ctx['phase']}",
        f"- **Status:** {ctx['phase_status']}",
        f"- **Budget consumed:** {ctx['budget_pct']}",
        f"- **Wall-clock since launch:** {ctx['wall_clock']}",
        f"- **ETA to next checkpoint:** {ctx['eta_checkpoint']}",
        "",
        "## Last 24 Hours",
        f"- **Runs completed:** {ctx['runs_completed']}",
        f"- **Current loss:** {ctx['current_loss']}",
        f"- **Eval results:** {ctx['eval_results']}",
        "",
        ctx["last_24h_summary"],
        "",
        "## Tier-2 Events (auto-recovered)",
    ]
    if ctx["tier2_events"]:
        for e in ctx["tier2_events"]:
            lines.append(f"- `{e.get('ts', '?')}` [{e.get('protocol', '?')}] {e.get('message', '')}")
    else:
        lines.append("_None._")

    lines += [
        "",
        "## Tier-1 Events (require human attention)",
    ]
    if ctx["tier1_events"]:
        for e in ctx["tier1_events"]:
            lines.append(f"- `{e.get('ts', '?')}` [{e.get('condition', '?')}] {e.get('message', '')}")
    else:
        lines.append("_None._")

    lines += [
        "",
        "## Pending Decisions (non-blocking)",
    ]
    if ctx["pending_decisions"]:
        for d in ctx["pending_decisions"]:
            lines.append(f"- `{d.get('ts', '?')}` **{d.get('question', '')}**")
            lines.append(f"  - Context: {d.get('context', '')}")
            lines.append(f"  - Default: {d.get('default_action', '')}")
    else:
        lines.append("_None._")

    lines += [
        "",
        "## Forecast",
        ctx["forecast"],
        "",
        "## Recent Plot",
        f"`{ctx['plot_path']}`",
        "",
    ]
    return "\n".join(lines)


def _format_duration(seconds: float) -> str:
    seconds = int(seconds)
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h}h {m}m {s}s"


def _within_hours(ts_iso: str, hours: int) -> bool:
    if not ts_iso:
        return False
    try:
        event_time = datetime.fromisoformat(ts_iso)
        if event_time.tzinfo is None:
            event_time = event_time.replace(tzinfo=timezone.utc)
        delta = datetime.now(timezone.utc) - event_time
        return delta.total_seconds() < hours * 3600
    except ValueError:
        return False


def _get_phase_cap(state: RunState, config: Any) -> float:
    """Return the wall-clock cap in hours for the current phase."""
    phase = state.current_phase
    if phase == 1:
        return float(getattr(config, "wall_clock_cap_hours", 4))
    if phase == 2:
        sweep = getattr(config, "sweep", None) or config
        return float(getattr(sweep, "wall_clock_cap_hours", 48))
    if phase == 3:
        return 24.0
    return 24.0
